alias: ViewAssist - Spell a Word
description: ""
trigger:
  - platform: conversation
    command:
      - "[please] [how do you| can you] spell {word}"
condition: []
action:
  - set_conversation_response: >-
      {{ trigger.slots.word }} is spelled  ... {% set spaced_text = '...
      '.join(trigger.slots.word) %}{{ spaced_text }}
  - if:
      - condition: template
        value_template: >-
          {% if target_satellite_device_type != 'audio_only' %}true{% else
          %}false{% endif %}
    then:
      - service: python_script.set_state
        data:
          entity_id: "{{ target_satellite_device }}"
          title: ""
          message: <center>{{ trigger.slots.word |upper }}</center>
          message_font_size: 6vw
      - service: browser_mod.navigate
        data:
          path: "{{ view }}"
        target:
          device_id: "{{ target_display_device }}"
      - service: input_text.set_value
        data:
          value: info
        target:
          entity_id: "{{ target_display_page_view }}"
variables:
  command_prompt: "[please] [how do you| can you] spell {word}"
  group_entity: group.viewassist_satellites
  view: /dashboard-viewassist/info
  target_satellite_device: |-
    {% for sat in expand(group_entity) %}
      {% if (device_id(sat.attributes.mic_device)  == trigger.device_id) or (device_id(sat.attributes.display_device)  == trigger.device_id) %}
        {{ sat.entity_id }}
      {% endif %}
    {% endfor %}
  target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
  target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
  target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type') }}"
  target_display_page_view: "{{ state_attr(target_satellite_device, 'page_view') }}"
mode: single
